"""Turn T2 findings into one GitHub-ready markdown file per finding.

    uv run python write_issues.py out/findings_openclaw.json out/signals_openclaw.json \
        out/issues openclaw

Every fact in the output comes from the report built by enriched.build_report,
so quotes keep their source URL and the counts stay the code-derived ones.
"""

from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

from assets import Issue, LovedFeature, RecommendedFeature, Signal, SignalFindings
from enriched import Report, RichIssue, Validation, build_report

_LABELS = {
    "issue": "bug",
    "recommended_feature": "enhancement",
    "loved_feature": "praise",
}


def _blockquote(text: str) -> str:
    """HackerNews bodies arrive as escaped HTML; markdown wants plain lines."""
    plain = html.unescape(re.sub(r"<p>", "\n", text))
    plain = html.unescape(re.sub(r"<[^>]+>", "", plain))
    return "\n".join(f"> {line}" if line.strip() else ">" for line in plain.splitlines())


def _slug(text: str) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", text.casefold())).strip("-")[:60]


def load_findings(path: Path) -> tuple[SignalFindings, dict[str, Validation]]:
    payload = json.loads(path.read_text())
    raw = payload.get("findings", payload)
    findings = SignalFindings(
        issues=[Issue(**d) for d in raw.get("issues", [])],
        recommended_features=[
            RecommendedFeature(**d) for d in raw.get("recommended_features", [])
        ],
        loved_features=[LovedFeature(**d) for d in raw.get("loved_features", [])],
    )
    validations = {
        v["finding_title"]: Validation(
            verdict=v["verdict"],
            explanation=v.get("explanation", ""),
            supported_signal_ids=v.get("supported_signal_ids", []),
            sources=v.get("sources", []),
        )
        for v in payload.get("validations", [])
    }
    return findings, validations


def render(item: RichIssue, product: str) -> str:
    lines = [f"# {item.title}", ""]

    meta = [f"**area:** {item.product_area}", f"**label:** {_LABELS[item.category]}"]
    if item.severity:
        meta.append(f"**severity:** {item.severity}")
    if item.priority:
        meta.append(f"**priority:** {item.priority}")
    lines += [" · ".join(meta), "", item.summary, ""]

    lines += ["## impact", ""]
    lines.append(f"- mentioned in {item.mention_count} distinct posts")
    lines.append(f"- reach (combined score of those posts): {item.reach}")
    if item.channels:
        lines.append(f"- channels: {', '.join(item.channels)}")
    if item.first_seen or item.last_seen:
        lines.append(f"- seen: {item.first_seen or '?'} → {item.last_seen or '?'}")
    lines.append("")

    if item.evidence:
        lines += ["## what people said", ""]
        for ev in item.evidence:
            attribution = " · ".join(
                p for p in [ev.author, ev.channel or ev.platform, ev.created_at] if p
            )
            lines.append(_blockquote(ev.quote))
            lines.append("")
            flag = "" if ev.verbatim else " — ⚠️ not found verbatim in the cited signal"
            lines.append(f"— [{attribution or ev.signal_id}]({ev.url}){flag}")
            lines.append("")

    if item.suggested_action:
        lines += ["## suggested action", "", item.suggested_action, ""]

    if item.related_code:
        lines += ["## related code", ""]
        for ref in item.related_code:
            where = ref.path + (f":{ref.line}" if ref.line else "")
            lines.append(f"- `{where}`" + (f" — {ref.reason}" if ref.reason else ""))
        lines.append("")

    if item.validation:
        lines += ["## validation", "", f"**{item.validation.verdict}** — {item.validation.explanation}", ""]
        for src in item.validation.sources:
            lines.append(f"- {src}")
        if item.validation.sources:
            lines.append("")

    lines += [
        "---",
        "",
        f"generated by fieldnotes from {item.mention_count} {product} signals · "
        f"finding id `{item.id}` · signals: {', '.join(item.signal_ids) or 'none'}",
        "",
    ]
    return "\n".join(lines)


def render_index(report: Report) -> str:
    lines = [
        f"# {report.product} — field notes",
        "",
        f"{len(report.issues)} issues · {len(report.recommended_features)} requested features · "
        f"{len(report.loved_features)} loved · health {report.health_score}/10 "
        f"· {report.signals_analyzed} signals analyzed · {report.generated_at}",
        "",
    ]
    for heading, items in [
        ("issues", report.issues),
        ("requested features", report.recommended_features),
        ("loved", report.loved_features),
    ]:
        if not items:
            continue
        lines += [f"## {heading}", ""]
        for item in items:
            sev = f"`{item.severity}` " if item.severity else ""
            lines.append(
                f"- {sev}[{item.title}]({_filename(item)}) — "
                f"{item.mention_count} mentions, reach {item.reach}"
            )
        lines.append("")
    return "\n".join(lines)


def _filename(item: RichIssue) -> str:
    return f"{item.id}-{_slug(item.title)}.md"


def main() -> None:
    findings_path = Path(sys.argv[1] if len(sys.argv) > 1 else "out/findings.json")
    signals_path = Path(sys.argv[2] if len(sys.argv) > 2 else "out/signals.json")
    dest = Path(sys.argv[3] if len(sys.argv) > 3 else "out/issues")
    product = sys.argv[4] if len(sys.argv) > 4 else signals_path.stem.replace("signals_", "")

    findings, validations = load_findings(findings_path)
    signals = [Signal.from_dict(d) for d in json.loads(signals_path.read_text())]
    report = build_report(findings, signals, product=product, validations=validations)

    dest.mkdir(parents=True, exist_ok=True)
    written = 0
    for item in report.issues + report.recommended_features + report.loved_features:
        (dest / _filename(item)).write_text(render(item, product))
        written += 1
    (dest / "README.md").write_text(render_index(report))

    print(f"wrote {written} markdown files + README.md to {dest}")


if __name__ == "__main__":
    main()
